apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-telemeter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-telemeter
subjects:
- kind: ServiceAccount
  name: prometheus-telemeter
  namespace: telemeter
