apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-telemeter
  namespace: telemeter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-telemeter
subjects:
- kind: ServiceAccount
  name: prometheus-telemeter
  namespace: telemeter
