apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: telemeter
    role: alert-rules
  name: prometheus-telemeter-rules
  namespace: telemeter
spec:
  groups: []
